[custom.all.rhone]
type   = "local"
path   = "."
ipkg   = "rhone.ipkg"
test   = "test/test.ipkg"

[custom.all.rhone-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.rhone-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"
